# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from webdriver_manager.chrome import ChromeDriverManager
from Constants import globalConstants
from pathlib import Path
from datetime import date

class TestTestpricelist():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
    self.folderPath = str(date.today())
    Path(self.folderPath).mkdir(exist_ok=True)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  


  def test_testpricelist(self):
    self.driver.get(globalConstants.URL)
    self.driver.maximize_window()
    self.driver.find_element(By.ID, globalConstants.user_id).click()
    self.driver.find_element(By.ID, globalConstants.user_id).send_keys("standard_user")
    self.driver.find_element(By.ID, globalConstants.password_id).click()
    self.driver.find_element(By.ID, globalConstants.password_id).send_keys("secret_sauce")
    self.driver.find_element(By.ID, globalConstants.login_id).click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-fleece-jacket\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-backpack\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".shopping_cart_badge").click()
    self.driver.find_element(By.ID, globalConstants.checkout_btn_id).click()
    self.driver.find_element(By.ID, globalConstants.checkout_first_name_id).click()
    self.driver.find_element(By.ID, globalConstants.checkout_first_name_id).send_keys("Seyma")
    self.driver.find_element(By.ID, globalConstants.checkout_last_name_id).click()
    self.driver.find_element(By.ID, globalConstants.checkout_last_name_id).send_keys("Karagoz")
    self.driver.find_element(By.ID, globalConstants.checkout_zipcode_id).click()
    self.driver.find_element(By.ID, globalConstants.checkout_zipcode_id).send_keys("00256")
    self.driver.find_element(By.ID, globalConstants.checkout_continue_btn_id).click()
    self.driver.find_element(By.ID, globalConstants.checkout_finish_btn_id).click()
    self.driver.find_element(By.ID, globalConstants.checkout_back_home_btn_id).click()
    self.driver.save_screenshot(f"{self.folderPath}/test-price-list.png")
  
